# Generated by Django 3.1.2 on 2020-11-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='sellOrBuy',
            field=models.IntegerField(choices=[(1, 'buy'), (2, 'sell')], default=1),
        ),
    ]
