# Generated by Django 3.1.2 on 2020-11-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_offer_sellorbuy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='prize',
            new_name='price',
        ),
    ]
